In [11]:
import pandas as pd
import numpy as np


In [ ]:
import os
import pandas as pd
import numpy as np

# directory containing experiment folders
base_path = "./data"

# subdirectory for a single run of the experiment 
# please adjust the following string to suite the experiment name
experiment_path = "experiment_dummy"
data_path = os.path.join(base_path, experiment_path)
print(f"Loading data from: {data_path}")

# data structure for all experiments
experiments = {}

# describes the frequency of data recording in seconds
# please adjust according to the frequency used in the experiment
data_frequency_s = 5

# describes the maximum observation time in seconds
# when experimenting, please keep the experiment running for at least this duration
# please adjust according to the duration of the experiment
max_observation_time_s = 60

# total number of data points expected
num_data_points = max_observation_time_s // data_frequency_s

# iterate over all subfolders in data_path
folders = sorted([f for f in os.listdir(data_path) if os.path.isdir(os.path.join(data_path, f))])

num_data_points = min(num_data_points, len(folders))
folders = folders[:num_data_points] # truncate to expected number of data points according to observation time

for folder in folders:
    folder_path = os.path.join(data_path, folder)
    
    # helper function to read
    def load_csv(filename):
        return pd.read_csv(os.path.join(folder_path, filename), header=None).values
    
    experiments[folder] = {
        "translation": load_csv("translation_vector.csv"),
        "quaternion": load_csv("rotation_quaternion.csv"),
    }

# check loaded data
first = folders[0]
print("Example experiment:", first)
print("Translation:\n", experiments[first]["translation"])
print("Quaternion:\n", experiments[first]["quaternion"])


Loading data from: ./data\experiment_dummy
Example experiment: 2025-08-20_13-59-59-Calibration
Translation:
 [[ 0.406796  -4.65559   -0.1434709]]
Quaternion:
 [[ 1.951740e-02 -3.633646e-04  6.118040e-01  7.907684e-01]]


In [13]:
# list of translation and rotation deltas
trans_list = []
rot_list = []

# populate lists with deltas
for experiment in experiments:
    trans_list.append(experiments[experiment]["translation"])
    rot_list.append(experiments[experiment]["quaternion"])

# check content of lists
print("Translations:", trans_list)
print("Rotations:", rot_list)

Translations: [array([[ 0.406796 , -4.65559  , -0.1434709]]), array([[ 0.4712639 , -4.701295  ,  0.06645274]]), array([[ 0.4961777 , -4.650855  , -0.00778246]]), array([[ 0.4370893 , -4.669846  , -0.05358064]]), array([[ 0.9882012, -4.456846 ,  1.135696 ]]), array([[ 0.8829817, -2.432189 , -0.9960982]]), array([[ 1.171723,  1.011395, -2.291482]]), array([[-1.441728, -5.52363 ,  1.549075]]), array([[1.377163, 1.305184, 2.716008]]), array([[ 0.5474403, -4.67673  ,  0.1424906]]), array([[ 1.559427 , -3.224504 , -0.4207628]]), array([[-1.289875, -4.052236,  3.545253]])]
Rotations: [array([[ 1.951740e-02, -3.633646e-04,  6.118040e-01,  7.907684e-01]]), array([[-0.00867065, -0.01046817,  0.6127312 ,  0.7901744 ]]), array([[-7.225851e-04, -1.350253e-02,  6.167302e-01,  7.870587e-01]]), array([[ 6.022003e-03, -2.049812e-04,  6.149529e-01,  7.885408e-01]]), array([[-0.208239 ,  0.5959325,  0.616026 ,  0.4711823]]), array([[0.2012866, 0.0244517, 0.8592632, 0.4696301]]), array([[ 0.3704765 , -0.0

In [14]:
# compute mean and stddev for translations
trans_mean = np.mean(trans_list, axis=0)
rot_mean = np.mean(rot_list, axis=0)

# compute stddev for translations
trans_stddev = np.std(trans_list, axis=0)
rot_stddev = np.std(rot_list, axis=0)

# check results
print("Mean Translation:\n", trans_mean)
print("Mean Quaternion:\n", rot_mean)
print("Translation StdDev:\n", trans_stddev)
print("Quaternion StdDev:\n", rot_stddev)

Mean Translation:
 [[ 0.46722167 -3.3939285   0.43681653]]
Mean Quaternion:
 [[0.11191568 0.15784577 0.47993997 0.44377141]]
Translation StdDev:
 [[0.89929743 2.17361792 1.5224331 ]]
Quaternion StdDev:
 [[0.28887881 0.39608823 0.33535276 0.42718358]]


In [15]:
# compute the distances in centimeters and degrees
translation_distance = np.linalg.norm(trans_mean)
rotation_degree = np.linalg.norm(rot_mean) * (180.0 / np.pi)  # convert radians to degrees

print("Mean Translation Magnitude (cm):", translation_distance)
print("Mean Rotation Magnitude (degrees):", rotation_degree)

Mean Translation Magnitude (cm): 3.4536727459619048
Mean Rotation Magnitude (degrees): 39.05857284804645
