In [2]:
import pandas as pd
import numpy as np


In [ ]:
import os
import pandas as pd
import numpy as np

# directory containing experiment folders
base_path = "./data"

# data structure for all experiments
experiments = {}

# iterate over all subfolders in base_path
folders = sorted([f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))])

for folder in folders:
    folder_path = os.path.join(base_path, folder)
    
    # helper function to read
    def load_csv(filename):
        return pd.read_csv(os.path.join(folder_path, filename), header=None).values
    
    experiments[folder] = {
        "rotation_matrix": load_csv("Rotation_matrix.csv"),
        "translation": load_csv("translation_vector.csv").flatten(),
        "quaternion": load_csv("rotation_quaternion.csv").flatten(),
        "hand_points": load_csv("matrix_Hand_Source.csv"),
        "demo_points": load_csv("matrix_Demonstrator_Source.csv"),
        "demo_points_transformed": load_csv("matrix_Demonstrator_Transformed.csv")
    }

# check
print(f"Loaded experiments: {len(experiments)}")
first = list(experiments.keys())[0]
print("Example experiment:", first)
print("Rotation matrix:\n", experiments[first]["rotation_matrix"])
print("Translation:", experiments[first]["translation"])


Geladene Experimente: 64
Beispiel Experiment: 2025-08-20_13-59-59-Calibration
Rotationsmatrix:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Translation: [ 0.406796  -4.65559   -0.1434709]
